# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 2.5.1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.legend import Legend  # noqa: E501
from swagger_client.rest import ApiException


class TestLegend(unittest.TestCase):
    """Legend unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLegend(self):
        """Test Legend"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.legend.Legend()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
