# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 2.5.1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.management_plane_api_nsx_component_administration_trust_management_csr_api import ManagementPlaneApiNsxComponentAdministrationTrustManagementCsrApi  # noqa: E501
from swagger_client.rest import ApiException


class TestManagementPlaneApiNsxComponentAdministrationTrustManagementCsrApi(unittest.TestCase):
    """ManagementPlaneApiNsxComponentAdministrationTrustManagementCsrApi unit test stubs"""

    def setUp(self):
        self.api = api.management_plane_api_nsx_component_administration_trust_management_csr_api.ManagementPlaneApiNsxComponentAdministrationTrustManagementCsrApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_csr(self):
        """Test case for delete_csr

        Delete a CSR  # noqa: E501
        """
        pass

    def test_generate_csr(self):
        """Test case for generate_csr

        Generate a New Certificate Signing Request  # noqa: E501
        """
        pass

    def test_get_csr(self):
        """Test case for get_csr

        Show CSR Data for the Given CSR ID  # noqa: E501
        """
        pass

    def test_get_csr_pem(self):
        """Test case for get_csr_pem

        Get CSR PEM File for the Given CSR ID  # noqa: E501
        """
        pass

    def test_get_csrs(self):
        """Test case for get_csrs

        Return All the Generated CSRs  # noqa: E501
        """
        pass

    def test_import_certificate_import(self):
        """Test case for import_certificate_import

        Import a Certificate Associated with an Approved CSR  # noqa: E501
        """
        pass

    def test_self_sign_certificate_self_sign(self):
        """Test case for self_sign_certificate_self_sign

        Self-Sign the CSR  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
