# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 2.5.1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.management_plane_api_migration_user_inputs_api import ManagementPlaneApiMigrationUserInputsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestManagementPlaneApiMigrationUserInputsApi(unittest.TestCase):
    """ManagementPlaneApiMigrationUserInputsApi unit test stubs"""

    def setUp(self):
        self.api = api.management_plane_api_migration_user_inputs_api.ManagementPlaneApiMigrationUserInputsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_discovered_switches(self):
        """Test case for get_discovered_switches

        Get the list of discovered switches (DVS, VSS)  # noqa: E501
        """
        pass

    def test_get_migrated_switches(self):
        """Test case for get_migrated_switches

        Get the list of migrated switches (DVS, VSS)  # noqa: E501
        """
        pass

    def test_get_migration_switch(self):
        """Test case for get_migration_switch

        Get the switch set as current scope for migration  # noqa: E501
        """
        pass

    def test_set_migration_switch(self):
        """Test case for set_migration_switch

        Set the switch as current scope for migration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
