# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 2.5.1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.app_profile_member_apps_csv_record import AppProfileMemberAppsCsvRecord  # noqa: E501
from swagger_client.rest import ApiException


class TestAppProfileMemberAppsCsvRecord(unittest.TestCase):
    """AppProfileMemberAppsCsvRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppProfileMemberAppsCsvRecord(self):
        """Test AppProfileMemberAppsCsvRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.app_profile_member_apps_csv_record.AppProfileMemberAppsCsvRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
