# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 2.5.1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.management_plane_api_troubleshooting_and_monitoring_healthcheck_api import ManagementPlaneApiTroubleshootingAndMonitoringHealthcheckApi  # noqa: E501
from swagger_client.rest import ApiException


class TestManagementPlaneApiTroubleshootingAndMonitoringHealthcheckApi(unittest.TestCase):
    """ManagementPlaneApiTroubleshootingAndMonitoringHealthcheckApi unit test stubs"""

    def setUp(self):
        self.api = api.management_plane_api_troubleshooting_and_monitoring_healthcheck_api.ManagementPlaneApiTroubleshootingAndMonitoringHealthcheckApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_manual_health_check(self):
        """Test case for create_manual_health_check

        Create a new manual health check request  # noqa: E501
        """
        pass

    def test_delete_manual_health_check(self):
        """Test case for delete_manual_health_check

        Delete an existing manual health check  # noqa: E501
        """
        pass

    def test_get_manual_health_check(self):
        """Test case for get_manual_health_check

        Get an existing manual health check  # noqa: E501
        """
        pass

    def test_list_manual_health_checks(self):
        """Test case for list_manual_health_checks

        List manual health checks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
