# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 2.5.1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ComputeCollectionTransportNodeTemplateState(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'compute_collection_id': 'str',
        'template_states': 'list[TransportNodeTemplateState]'
    }

    attribute_map = {
        'compute_collection_id': 'compute_collection_id',
        'template_states': 'template_states'
    }

    def __init__(self, compute_collection_id=None, template_states=None):  # noqa: E501
        """ComputeCollectionTransportNodeTemplateState - a model defined in Swagger"""  # noqa: E501
        self._compute_collection_id = None
        self._template_states = None
        self.discriminator = None
        if compute_collection_id is not None:
            self.compute_collection_id = compute_collection_id
        if template_states is not None:
            self.template_states = template_states

    @property
    def compute_collection_id(self):
        """Gets the compute_collection_id of this ComputeCollectionTransportNodeTemplateState.  # noqa: E501

        Associated compute collection id  # noqa: E501

        :return: The compute_collection_id of this ComputeCollectionTransportNodeTemplateState.  # noqa: E501
        :rtype: str
        """
        return self._compute_collection_id

    @compute_collection_id.setter
    def compute_collection_id(self, compute_collection_id):
        """Sets the compute_collection_id of this ComputeCollectionTransportNodeTemplateState.

        Associated compute collection id  # noqa: E501

        :param compute_collection_id: The compute_collection_id of this ComputeCollectionTransportNodeTemplateState.  # noqa: E501
        :type: str
        """

        self._compute_collection_id = compute_collection_id

    @property
    def template_states(self):
        """Gets the template_states of this ComputeCollectionTransportNodeTemplateState.  # noqa: E501

        Transport node template states in compute collection  # noqa: E501

        :return: The template_states of this ComputeCollectionTransportNodeTemplateState.  # noqa: E501
        :rtype: list[TransportNodeTemplateState]
        """
        return self._template_states

    @template_states.setter
    def template_states(self, template_states):
        """Sets the template_states of this ComputeCollectionTransportNodeTemplateState.

        Transport node template states in compute collection  # noqa: E501

        :param template_states: The template_states of this ComputeCollectionTransportNodeTemplateState.  # noqa: E501
        :type: list[TransportNodeTemplateState]
        """

        self._template_states = template_states

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComputeCollectionTransportNodeTemplateState, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComputeCollectionTransportNodeTemplateState):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
