# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 2.5.1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ContainerCluster(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'last_sync_time': 'int',
        'display_name': 'str',
        'description': 'str',
        'resource_type': 'str',
        'tags': 'list[Tag]',
        'cluster_type': 'str',
        'origin_properties': 'list[KeyValuePair]',
        'external_id': 'str',
        'infrastructure': 'ContainerInfrastructureInfo'
    }
    if hasattr(DiscoveredResource, "swagger_types"):
        swagger_types.update(DiscoveredResource.swagger_types)

    attribute_map = {
        'last_sync_time': '_last_sync_time',
        'display_name': 'display_name',
        'description': 'description',
        'resource_type': 'resource_type',
        'tags': 'tags',
        'cluster_type': 'cluster_type',
        'origin_properties': 'origin_properties',
        'external_id': 'external_id',
        'infrastructure': 'infrastructure'
    }
    if hasattr(DiscoveredResource, "attribute_map"):
        attribute_map.update(DiscoveredResource.attribute_map)

    def __init__(self, last_sync_time=None, display_name=None, description=None, resource_type=None, tags=None, cluster_type=None, origin_properties=None, external_id=None, infrastructure=None, *args, **kwargs):  # noqa: E501
        """ContainerCluster - a model defined in Swagger"""  # noqa: E501
        self._last_sync_time = None
        self._display_name = None
        self._description = None
        self._resource_type = None
        self._tags = None
        self._cluster_type = None
        self._origin_properties = None
        self._external_id = None
        self._infrastructure = None
        self.discriminator = None
        if last_sync_time is not None:
            self.last_sync_time = last_sync_time
        if display_name is not None:
            self.display_name = display_name
        if description is not None:
            self.description = description
        self.resource_type = resource_type
        if tags is not None:
            self.tags = tags
        if cluster_type is not None:
            self.cluster_type = cluster_type
        if origin_properties is not None:
            self.origin_properties = origin_properties
        if external_id is not None:
            self.external_id = external_id
        if infrastructure is not None:
            self.infrastructure = infrastructure
        DiscoveredResource.__init__(self, *args, **kwargs)

    @property
    def last_sync_time(self):
        """Gets the last_sync_time of this ContainerCluster.  # noqa: E501

        Timestamp of last modification  # noqa: E501

        :return: The last_sync_time of this ContainerCluster.  # noqa: E501
        :rtype: int
        """
        return self._last_sync_time

    @last_sync_time.setter
    def last_sync_time(self, last_sync_time):
        """Sets the last_sync_time of this ContainerCluster.

        Timestamp of last modification  # noqa: E501

        :param last_sync_time: The last_sync_time of this ContainerCluster.  # noqa: E501
        :type: int
        """

        self._last_sync_time = last_sync_time

    @property
    def display_name(self):
        """Gets the display_name of this ContainerCluster.  # noqa: E501

        Defaults to ID if not set  # noqa: E501

        :return: The display_name of this ContainerCluster.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this ContainerCluster.

        Defaults to ID if not set  # noqa: E501

        :param display_name: The display_name of this ContainerCluster.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def description(self):
        """Gets the description of this ContainerCluster.  # noqa: E501

        Description of this resource  # noqa: E501

        :return: The description of this ContainerCluster.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ContainerCluster.

        Description of this resource  # noqa: E501

        :param description: The description of this ContainerCluster.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def resource_type(self):
        """Gets the resource_type of this ContainerCluster.  # noqa: E501

        The type of this resource.  # noqa: E501

        :return: The resource_type of this ContainerCluster.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this ContainerCluster.

        The type of this resource.  # noqa: E501

        :param resource_type: The resource_type of this ContainerCluster.  # noqa: E501
        :type: str
        """
        if resource_type is None:
            raise ValueError("Invalid value for `resource_type`, must not be `None`")  # noqa: E501

        self._resource_type = resource_type

    @property
    def tags(self):
        """Gets the tags of this ContainerCluster.  # noqa: E501

        Opaque identifiers meaningful to the API user  # noqa: E501

        :return: The tags of this ContainerCluster.  # noqa: E501
        :rtype: list[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this ContainerCluster.

        Opaque identifiers meaningful to the API user  # noqa: E501

        :param tags: The tags of this ContainerCluster.  # noqa: E501
        :type: list[Tag]
        """

        self._tags = tags

    @property
    def cluster_type(self):
        """Gets the cluster_type of this ContainerCluster.  # noqa: E501

        Type of the container cluster. In case of creating container cluster first time, it is expected to pass the valid cluster-type. In case of update, if there is no change in cluster-type, then this field can be omitted in the request.   # noqa: E501

        :return: The cluster_type of this ContainerCluster.  # noqa: E501
        :rtype: str
        """
        return self._cluster_type

    @cluster_type.setter
    def cluster_type(self, cluster_type):
        """Sets the cluster_type of this ContainerCluster.

        Type of the container cluster. In case of creating container cluster first time, it is expected to pass the valid cluster-type. In case of update, if there is no change in cluster-type, then this field can be omitted in the request.   # noqa: E501

        :param cluster_type: The cluster_type of this ContainerCluster.  # noqa: E501
        :type: str
        """
        allowed_values = ["PAS", "PKS", "Kubernetes", "Openshift", "WCP", "Other"]  # noqa: E501
        if cluster_type not in allowed_values:
            raise ValueError(
                "Invalid value for `cluster_type` ({0}), must be one of {1}"  # noqa: E501
                .format(cluster_type, allowed_values)
            )

        self._cluster_type = cluster_type

    @property
    def origin_properties(self):
        """Gets the origin_properties of this ContainerCluster.  # noqa: E501

        Array of additional specific properties of container cluster in key-value format.   # noqa: E501

        :return: The origin_properties of this ContainerCluster.  # noqa: E501
        :rtype: list[KeyValuePair]
        """
        return self._origin_properties

    @origin_properties.setter
    def origin_properties(self, origin_properties):
        """Sets the origin_properties of this ContainerCluster.

        Array of additional specific properties of container cluster in key-value format.   # noqa: E501

        :param origin_properties: The origin_properties of this ContainerCluster.  # noqa: E501
        :type: list[KeyValuePair]
        """

        self._origin_properties = origin_properties

    @property
    def external_id(self):
        """Gets the external_id of this ContainerCluster.  # noqa: E501

        External identifier of the container cluster.  # noqa: E501

        :return: The external_id of this ContainerCluster.  # noqa: E501
        :rtype: str
        """
        return self._external_id

    @external_id.setter
    def external_id(self, external_id):
        """Sets the external_id of this ContainerCluster.

        External identifier of the container cluster.  # noqa: E501

        :param external_id: The external_id of this ContainerCluster.  # noqa: E501
        :type: str
        """

        self._external_id = external_id

    @property
    def infrastructure(self):
        """Gets the infrastructure of this ContainerCluster.  # noqa: E501


        :return: The infrastructure of this ContainerCluster.  # noqa: E501
        :rtype: ContainerInfrastructureInfo
        """
        return self._infrastructure

    @infrastructure.setter
    def infrastructure(self, infrastructure):
        """Sets the infrastructure of this ContainerCluster.


        :param infrastructure: The infrastructure of this ContainerCluster.  # noqa: E501
        :type: ContainerInfrastructureInfo
        """

        self._infrastructure = infrastructure

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContainerCluster, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContainerCluster):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
