# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 2.5.1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class MigrationUnitGroupAggregateInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'system_owned': 'bool',
        'display_name': 'str',
        'description': 'str',
        'tags': 'list[Tag]',
        'create_user': 'str',
        'protection': 'str',
        'create_time': 'int',
        'last_modified_time': 'int',
        'last_modified_user': 'str',
        'id': 'str',
        'resource_type': 'str',
        'status': 'str',
        'failed_count': 'int',
        'group': 'MigrationUnitGroup',
        'percent_complete': 'float'
    }
    if hasattr(ManagedResource, "swagger_types"):
        swagger_types.update(ManagedResource.swagger_types)

    attribute_map = {
        'system_owned': '_system_owned',
        'display_name': 'display_name',
        'description': 'description',
        'tags': 'tags',
        'create_user': '_create_user',
        'protection': '_protection',
        'create_time': '_create_time',
        'last_modified_time': '_last_modified_time',
        'last_modified_user': '_last_modified_user',
        'id': 'id',
        'resource_type': 'resource_type',
        'status': 'status',
        'failed_count': 'failed_count',
        'group': 'group',
        'percent_complete': 'percent_complete'
    }
    if hasattr(ManagedResource, "attribute_map"):
        attribute_map.update(ManagedResource.attribute_map)

    def __init__(self, system_owned=None, display_name=None, description=None, tags=None, create_user=None, protection=None, create_time=None, last_modified_time=None, last_modified_user=None, id=None, resource_type=None, status=None, failed_count=None, group=None, percent_complete=None, *args, **kwargs):  # noqa: E501
        """MigrationUnitGroupAggregateInfo - a model defined in Swagger"""  # noqa: E501
        self._system_owned = None
        self._display_name = None
        self._description = None
        self._tags = None
        self._create_user = None
        self._protection = None
        self._create_time = None
        self._last_modified_time = None
        self._last_modified_user = None
        self._id = None
        self._resource_type = None
        self._status = None
        self._failed_count = None
        self._group = None
        self._percent_complete = None
        self.discriminator = None
        if system_owned is not None:
            self.system_owned = system_owned
        if display_name is not None:
            self.display_name = display_name
        if description is not None:
            self.description = description
        if tags is not None:
            self.tags = tags
        if create_user is not None:
            self.create_user = create_user
        if protection is not None:
            self.protection = protection
        if create_time is not None:
            self.create_time = create_time
        if last_modified_time is not None:
            self.last_modified_time = last_modified_time
        if last_modified_user is not None:
            self.last_modified_user = last_modified_user
        if id is not None:
            self.id = id
        if resource_type is not None:
            self.resource_type = resource_type
        if status is not None:
            self.status = status
        if failed_count is not None:
            self.failed_count = failed_count
        self.group = group
        if percent_complete is not None:
            self.percent_complete = percent_complete
        ManagedResource.__init__(self, *args, **kwargs)

    @property
    def system_owned(self):
        """Gets the system_owned of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        Indicates system owned resource  # noqa: E501

        :return: The system_owned of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: bool
        """
        return self._system_owned

    @system_owned.setter
    def system_owned(self, system_owned):
        """Sets the system_owned of this MigrationUnitGroupAggregateInfo.

        Indicates system owned resource  # noqa: E501

        :param system_owned: The system_owned of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: bool
        """

        self._system_owned = system_owned

    @property
    def display_name(self):
        """Gets the display_name of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        Defaults to ID if not set  # noqa: E501

        :return: The display_name of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this MigrationUnitGroupAggregateInfo.

        Defaults to ID if not set  # noqa: E501

        :param display_name: The display_name of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def description(self):
        """Gets the description of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        Description of this resource  # noqa: E501

        :return: The description of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this MigrationUnitGroupAggregateInfo.

        Description of this resource  # noqa: E501

        :param description: The description of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def tags(self):
        """Gets the tags of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        Opaque identifiers meaningful to the API user  # noqa: E501

        :return: The tags of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: list[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this MigrationUnitGroupAggregateInfo.

        Opaque identifiers meaningful to the API user  # noqa: E501

        :param tags: The tags of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: list[Tag]
        """

        self._tags = tags

    @property
    def create_user(self):
        """Gets the create_user of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        ID of the user who created this resource  # noqa: E501

        :return: The create_user of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: str
        """
        return self._create_user

    @create_user.setter
    def create_user(self, create_user):
        """Sets the create_user of this MigrationUnitGroupAggregateInfo.

        ID of the user who created this resource  # noqa: E501

        :param create_user: The create_user of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: str
        """

        self._create_user = create_user

    @property
    def protection(self):
        """Gets the protection of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        Protection status is one of the following: PROTECTED - the client who retrieved the entity is not allowed             to modify it. NOT_PROTECTED - the client who retrieved the entity is allowed                 to modify it REQUIRE_OVERRIDE - the client who retrieved the entity is a super                    user and can modify it, but only when providing                    the request header X-Allow-Overwrite=true. UNKNOWN - the _protection field could not be determined for this           entity.   # noqa: E501

        :return: The protection of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: str
        """
        return self._protection

    @protection.setter
    def protection(self, protection):
        """Sets the protection of this MigrationUnitGroupAggregateInfo.

        Protection status is one of the following: PROTECTED - the client who retrieved the entity is not allowed             to modify it. NOT_PROTECTED - the client who retrieved the entity is allowed                 to modify it REQUIRE_OVERRIDE - the client who retrieved the entity is a super                    user and can modify it, but only when providing                    the request header X-Allow-Overwrite=true. UNKNOWN - the _protection field could not be determined for this           entity.   # noqa: E501

        :param protection: The protection of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: str
        """

        self._protection = protection

    @property
    def create_time(self):
        """Gets the create_time of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        Timestamp of resource creation  # noqa: E501

        :return: The create_time of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: int
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this MigrationUnitGroupAggregateInfo.

        Timestamp of resource creation  # noqa: E501

        :param create_time: The create_time of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: int
        """

        self._create_time = create_time

    @property
    def last_modified_time(self):
        """Gets the last_modified_time of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        Timestamp of last modification  # noqa: E501

        :return: The last_modified_time of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: int
        """
        return self._last_modified_time

    @last_modified_time.setter
    def last_modified_time(self, last_modified_time):
        """Sets the last_modified_time of this MigrationUnitGroupAggregateInfo.

        Timestamp of last modification  # noqa: E501

        :param last_modified_time: The last_modified_time of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: int
        """

        self._last_modified_time = last_modified_time

    @property
    def last_modified_user(self):
        """Gets the last_modified_user of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        ID of the user who last modified this resource  # noqa: E501

        :return: The last_modified_user of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: str
        """
        return self._last_modified_user

    @last_modified_user.setter
    def last_modified_user(self, last_modified_user):
        """Sets the last_modified_user of this MigrationUnitGroupAggregateInfo.

        ID of the user who last modified this resource  # noqa: E501

        :param last_modified_user: The last_modified_user of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: str
        """

        self._last_modified_user = last_modified_user

    @property
    def id(self):
        """Gets the id of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        Unique identifier of this resource  # noqa: E501

        :return: The id of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MigrationUnitGroupAggregateInfo.

        Unique identifier of this resource  # noqa: E501

        :param id: The id of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def resource_type(self):
        """Gets the resource_type of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        The type of this resource.  # noqa: E501

        :return: The resource_type of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this MigrationUnitGroupAggregateInfo.

        The type of this resource.  # noqa: E501

        :param resource_type: The resource_type of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def status(self):
        """Gets the status of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        Migration status of migration unit group  # noqa: E501

        :return: The status of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this MigrationUnitGroupAggregateInfo.

        Migration status of migration unit group  # noqa: E501

        :param status: The status of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: str
        """
        allowed_values = ["SUCCESS", "FAILED", "IN_PROGRESS", "NOT_STARTED", "PAUSED"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def failed_count(self):
        """Gets the failed_count of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        Number of nodes in the migration unit group that failed migration  # noqa: E501

        :return: The failed_count of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: int
        """
        return self._failed_count

    @failed_count.setter
    def failed_count(self, failed_count):
        """Sets the failed_count of this MigrationUnitGroupAggregateInfo.

        Number of nodes in the migration unit group that failed migration  # noqa: E501

        :param failed_count: The failed_count of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: int
        """

        self._failed_count = failed_count

    @property
    def group(self):
        """Gets the group of this MigrationUnitGroupAggregateInfo.  # noqa: E501


        :return: The group of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: MigrationUnitGroup
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this MigrationUnitGroupAggregateInfo.


        :param group: The group of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: MigrationUnitGroup
        """
        if group is None:
            raise ValueError("Invalid value for `group`, must not be `None`")  # noqa: E501

        self._group = group

    @property
    def percent_complete(self):
        """Gets the percent_complete of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        Indicator of migration progress in percentage  # noqa: E501

        :return: The percent_complete of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: float
        """
        return self._percent_complete

    @percent_complete.setter
    def percent_complete(self, percent_complete):
        """Sets the percent_complete of this MigrationUnitGroupAggregateInfo.

        Indicator of migration progress in percentage  # noqa: E501

        :param percent_complete: The percent_complete of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: float
        """

        self._percent_complete = percent_complete

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MigrationUnitGroupAggregateInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MigrationUnitGroupAggregateInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
