# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 2.5.1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ServiceChain(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'system_owned': 'bool',
        'display_name': 'str',
        'description': 'str',
        'tags': 'list[Tag]',
        'create_user': 'str',
        'protection': 'str',
        'create_time': 'int',
        'last_modified_time': 'int',
        'last_modified_user': 'str',
        'id': 'str',
        'resource_type': 'str',
        'reverse_path_service_profiles': 'list[ResourceReference]',
        'service_attachments': 'list[ResourceReference]',
        'forward_path_service_profiles': 'list[ResourceReference]',
        'service_chain_id': 'str',
        'path_selection_policy': 'str',
        'on_failure_policy': 'str'
    }
    if hasattr(ManagedResource, "swagger_types"):
        swagger_types.update(ManagedResource.swagger_types)

    attribute_map = {
        'system_owned': '_system_owned',
        'display_name': 'display_name',
        'description': 'description',
        'tags': 'tags',
        'create_user': '_create_user',
        'protection': '_protection',
        'create_time': '_create_time',
        'last_modified_time': '_last_modified_time',
        'last_modified_user': '_last_modified_user',
        'id': 'id',
        'resource_type': 'resource_type',
        'reverse_path_service_profiles': 'reverse_path_service_profiles',
        'service_attachments': 'service_attachments',
        'forward_path_service_profiles': 'forward_path_service_profiles',
        'service_chain_id': 'service_chain_id',
        'path_selection_policy': 'path_selection_policy',
        'on_failure_policy': 'on_failure_policy'
    }
    if hasattr(ManagedResource, "attribute_map"):
        attribute_map.update(ManagedResource.attribute_map)

    def __init__(self, system_owned=None, display_name=None, description=None, tags=None, create_user=None, protection=None, create_time=None, last_modified_time=None, last_modified_user=None, id=None, resource_type=None, reverse_path_service_profiles=None, service_attachments=None, forward_path_service_profiles=None, service_chain_id=None, path_selection_policy='ANY', on_failure_policy='ALLOW', *args, **kwargs):  # noqa: E501
        """ServiceChain - a model defined in Swagger"""  # noqa: E501
        self._system_owned = None
        self._display_name = None
        self._description = None
        self._tags = None
        self._create_user = None
        self._protection = None
        self._create_time = None
        self._last_modified_time = None
        self._last_modified_user = None
        self._id = None
        self._resource_type = None
        self._reverse_path_service_profiles = None
        self._service_attachments = None
        self._forward_path_service_profiles = None
        self._service_chain_id = None
        self._path_selection_policy = None
        self._on_failure_policy = None
        self.discriminator = None
        if system_owned is not None:
            self.system_owned = system_owned
        if display_name is not None:
            self.display_name = display_name
        if description is not None:
            self.description = description
        if tags is not None:
            self.tags = tags
        if create_user is not None:
            self.create_user = create_user
        if protection is not None:
            self.protection = protection
        if create_time is not None:
            self.create_time = create_time
        if last_modified_time is not None:
            self.last_modified_time = last_modified_time
        if last_modified_user is not None:
            self.last_modified_user = last_modified_user
        if id is not None:
            self.id = id
        if resource_type is not None:
            self.resource_type = resource_type
        if reverse_path_service_profiles is not None:
            self.reverse_path_service_profiles = reverse_path_service_profiles
        self.service_attachments = service_attachments
        self.forward_path_service_profiles = forward_path_service_profiles
        if service_chain_id is not None:
            self.service_chain_id = service_chain_id
        if path_selection_policy is not None:
            self.path_selection_policy = path_selection_policy
        if on_failure_policy is not None:
            self.on_failure_policy = on_failure_policy
        ManagedResource.__init__(self, *args, **kwargs)

    @property
    def system_owned(self):
        """Gets the system_owned of this ServiceChain.  # noqa: E501

        Indicates system owned resource  # noqa: E501

        :return: The system_owned of this ServiceChain.  # noqa: E501
        :rtype: bool
        """
        return self._system_owned

    @system_owned.setter
    def system_owned(self, system_owned):
        """Sets the system_owned of this ServiceChain.

        Indicates system owned resource  # noqa: E501

        :param system_owned: The system_owned of this ServiceChain.  # noqa: E501
        :type: bool
        """

        self._system_owned = system_owned

    @property
    def display_name(self):
        """Gets the display_name of this ServiceChain.  # noqa: E501

        Defaults to ID if not set  # noqa: E501

        :return: The display_name of this ServiceChain.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this ServiceChain.

        Defaults to ID if not set  # noqa: E501

        :param display_name: The display_name of this ServiceChain.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def description(self):
        """Gets the description of this ServiceChain.  # noqa: E501

        Description of this resource  # noqa: E501

        :return: The description of this ServiceChain.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ServiceChain.

        Description of this resource  # noqa: E501

        :param description: The description of this ServiceChain.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def tags(self):
        """Gets the tags of this ServiceChain.  # noqa: E501

        Opaque identifiers meaningful to the API user  # noqa: E501

        :return: The tags of this ServiceChain.  # noqa: E501
        :rtype: list[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this ServiceChain.

        Opaque identifiers meaningful to the API user  # noqa: E501

        :param tags: The tags of this ServiceChain.  # noqa: E501
        :type: list[Tag]
        """

        self._tags = tags

    @property
    def create_user(self):
        """Gets the create_user of this ServiceChain.  # noqa: E501

        ID of the user who created this resource  # noqa: E501

        :return: The create_user of this ServiceChain.  # noqa: E501
        :rtype: str
        """
        return self._create_user

    @create_user.setter
    def create_user(self, create_user):
        """Sets the create_user of this ServiceChain.

        ID of the user who created this resource  # noqa: E501

        :param create_user: The create_user of this ServiceChain.  # noqa: E501
        :type: str
        """

        self._create_user = create_user

    @property
    def protection(self):
        """Gets the protection of this ServiceChain.  # noqa: E501

        Protection status is one of the following: PROTECTED - the client who retrieved the entity is not allowed             to modify it. NOT_PROTECTED - the client who retrieved the entity is allowed                 to modify it REQUIRE_OVERRIDE - the client who retrieved the entity is a super                    user and can modify it, but only when providing                    the request header X-Allow-Overwrite=true. UNKNOWN - the _protection field could not be determined for this           entity.   # noqa: E501

        :return: The protection of this ServiceChain.  # noqa: E501
        :rtype: str
        """
        return self._protection

    @protection.setter
    def protection(self, protection):
        """Sets the protection of this ServiceChain.

        Protection status is one of the following: PROTECTED - the client who retrieved the entity is not allowed             to modify it. NOT_PROTECTED - the client who retrieved the entity is allowed                 to modify it REQUIRE_OVERRIDE - the client who retrieved the entity is a super                    user and can modify it, but only when providing                    the request header X-Allow-Overwrite=true. UNKNOWN - the _protection field could not be determined for this           entity.   # noqa: E501

        :param protection: The protection of this ServiceChain.  # noqa: E501
        :type: str
        """

        self._protection = protection

    @property
    def create_time(self):
        """Gets the create_time of this ServiceChain.  # noqa: E501

        Timestamp of resource creation  # noqa: E501

        :return: The create_time of this ServiceChain.  # noqa: E501
        :rtype: int
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this ServiceChain.

        Timestamp of resource creation  # noqa: E501

        :param create_time: The create_time of this ServiceChain.  # noqa: E501
        :type: int
        """

        self._create_time = create_time

    @property
    def last_modified_time(self):
        """Gets the last_modified_time of this ServiceChain.  # noqa: E501

        Timestamp of last modification  # noqa: E501

        :return: The last_modified_time of this ServiceChain.  # noqa: E501
        :rtype: int
        """
        return self._last_modified_time

    @last_modified_time.setter
    def last_modified_time(self, last_modified_time):
        """Sets the last_modified_time of this ServiceChain.

        Timestamp of last modification  # noqa: E501

        :param last_modified_time: The last_modified_time of this ServiceChain.  # noqa: E501
        :type: int
        """

        self._last_modified_time = last_modified_time

    @property
    def last_modified_user(self):
        """Gets the last_modified_user of this ServiceChain.  # noqa: E501

        ID of the user who last modified this resource  # noqa: E501

        :return: The last_modified_user of this ServiceChain.  # noqa: E501
        :rtype: str
        """
        return self._last_modified_user

    @last_modified_user.setter
    def last_modified_user(self, last_modified_user):
        """Sets the last_modified_user of this ServiceChain.

        ID of the user who last modified this resource  # noqa: E501

        :param last_modified_user: The last_modified_user of this ServiceChain.  # noqa: E501
        :type: str
        """

        self._last_modified_user = last_modified_user

    @property
    def id(self):
        """Gets the id of this ServiceChain.  # noqa: E501

        Unique identifier of this resource  # noqa: E501

        :return: The id of this ServiceChain.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ServiceChain.

        Unique identifier of this resource  # noqa: E501

        :param id: The id of this ServiceChain.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def resource_type(self):
        """Gets the resource_type of this ServiceChain.  # noqa: E501

        The type of this resource.  # noqa: E501

        :return: The resource_type of this ServiceChain.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this ServiceChain.

        The type of this resource.  # noqa: E501

        :param resource_type: The resource_type of this ServiceChain.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def reverse_path_service_profiles(self):
        """Gets the reverse_path_service_profiles of this ServiceChain.  # noqa: E501

        List of ServiceInsertionServiceProfiles id. Reverse path service profiles are applied to egress traffic and is optional. 2 different set of profiles can be defined for forward and reverse path. If not defined, the reverse of the forward path service profile is applied.  # noqa: E501

        :return: The reverse_path_service_profiles of this ServiceChain.  # noqa: E501
        :rtype: list[ResourceReference]
        """
        return self._reverse_path_service_profiles

    @reverse_path_service_profiles.setter
    def reverse_path_service_profiles(self, reverse_path_service_profiles):
        """Sets the reverse_path_service_profiles of this ServiceChain.

        List of ServiceInsertionServiceProfiles id. Reverse path service profiles are applied to egress traffic and is optional. 2 different set of profiles can be defined for forward and reverse path. If not defined, the reverse of the forward path service profile is applied.  # noqa: E501

        :param reverse_path_service_profiles: The reverse_path_service_profiles of this ServiceChain.  # noqa: E501
        :type: list[ResourceReference]
        """

        self._reverse_path_service_profiles = reverse_path_service_profiles

    @property
    def service_attachments(self):
        """Gets the service_attachments of this ServiceChain.  # noqa: E501

        Service attachment specifies the scope i.e Service plane at which the SVMs are deployed.  # noqa: E501

        :return: The service_attachments of this ServiceChain.  # noqa: E501
        :rtype: list[ResourceReference]
        """
        return self._service_attachments

    @service_attachments.setter
    def service_attachments(self, service_attachments):
        """Sets the service_attachments of this ServiceChain.

        Service attachment specifies the scope i.e Service plane at which the SVMs are deployed.  # noqa: E501

        :param service_attachments: The service_attachments of this ServiceChain.  # noqa: E501
        :type: list[ResourceReference]
        """
        if service_attachments is None:
            raise ValueError("Invalid value for `service_attachments`, must not be `None`")  # noqa: E501

        self._service_attachments = service_attachments

    @property
    def forward_path_service_profiles(self):
        """Gets the forward_path_service_profiles of this ServiceChain.  # noqa: E501

        List of ServiceInsertionServiceProfiles that constitutes the the service chain. The forward path service profiles are applied to ingress traffic.  # noqa: E501

        :return: The forward_path_service_profiles of this ServiceChain.  # noqa: E501
        :rtype: list[ResourceReference]
        """
        return self._forward_path_service_profiles

    @forward_path_service_profiles.setter
    def forward_path_service_profiles(self, forward_path_service_profiles):
        """Sets the forward_path_service_profiles of this ServiceChain.

        List of ServiceInsertionServiceProfiles that constitutes the the service chain. The forward path service profiles are applied to ingress traffic.  # noqa: E501

        :param forward_path_service_profiles: The forward_path_service_profiles of this ServiceChain.  # noqa: E501
        :type: list[ResourceReference]
        """
        if forward_path_service_profiles is None:
            raise ValueError("Invalid value for `forward_path_service_profiles`, must not be `None`")  # noqa: E501

        self._forward_path_service_profiles = forward_path_service_profiles

    @property
    def service_chain_id(self):
        """Gets the service_chain_id of this ServiceChain.  # noqa: E501

        A unique id generated for every service chain. This is not a uuid.  # noqa: E501

        :return: The service_chain_id of this ServiceChain.  # noqa: E501
        :rtype: str
        """
        return self._service_chain_id

    @service_chain_id.setter
    def service_chain_id(self, service_chain_id):
        """Sets the service_chain_id of this ServiceChain.

        A unique id generated for every service chain. This is not a uuid.  # noqa: E501

        :param service_chain_id: The service_chain_id of this ServiceChain.  # noqa: E501
        :type: str
        """

        self._service_chain_id = service_chain_id

    @property
    def path_selection_policy(self):
        """Gets the path_selection_policy of this ServiceChain.  # noqa: E501

        Path selection policy can be - ANY - Service Insertion is free to redirect to any service path regardless of any load balancing considerations or flow pinning. LOCAL - means to prefer local service insances. REMOTE - preference is to redirect to the SVM co-located on the same host.  # noqa: E501

        :return: The path_selection_policy of this ServiceChain.  # noqa: E501
        :rtype: str
        """
        return self._path_selection_policy

    @path_selection_policy.setter
    def path_selection_policy(self, path_selection_policy):
        """Sets the path_selection_policy of this ServiceChain.

        Path selection policy can be - ANY - Service Insertion is free to redirect to any service path regardless of any load balancing considerations or flow pinning. LOCAL - means to prefer local service insances. REMOTE - preference is to redirect to the SVM co-located on the same host.  # noqa: E501

        :param path_selection_policy: The path_selection_policy of this ServiceChain.  # noqa: E501
        :type: str
        """
        allowed_values = ["ANY", "LOCAL", "REMOTE"]  # noqa: E501
        if path_selection_policy not in allowed_values:
            raise ValueError(
                "Invalid value for `path_selection_policy` ({0}), must be one of {1}"  # noqa: E501
                .format(path_selection_policy, allowed_values)
            )

        self._path_selection_policy = path_selection_policy

    @property
    def on_failure_policy(self):
        """Gets the on_failure_policy of this ServiceChain.  # noqa: E501

        Failure policy for the service tells datapath, the action to take i.e to allow or block traffic during failure scenarios.  # noqa: E501

        :return: The on_failure_policy of this ServiceChain.  # noqa: E501
        :rtype: str
        """
        return self._on_failure_policy

    @on_failure_policy.setter
    def on_failure_policy(self, on_failure_policy):
        """Sets the on_failure_policy of this ServiceChain.

        Failure policy for the service tells datapath, the action to take i.e to allow or block traffic during failure scenarios.  # noqa: E501

        :param on_failure_policy: The on_failure_policy of this ServiceChain.  # noqa: E501
        :type: str
        """
        allowed_values = ["ALLOW", "BLOCK"]  # noqa: E501
        if on_failure_policy not in allowed_values:
            raise ValueError(
                "Invalid value for `on_failure_policy` ({0}), must be one of {1}"  # noqa: E501
                .format(on_failure_policy, allowed_values)
            )

        self._on_failure_policy = on_failure_policy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServiceChain, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServiceChain):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
