# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 2.5.1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class SshKeyProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'password': 'str',
        'label': 'str',
        'type': 'str',
        'value': 'str'
    }
    if hasattr(SshKeyBaseProperties, "swagger_types"):
        swagger_types.update(SshKeyBaseProperties.swagger_types)

    attribute_map = {
        'password': 'password',
        'label': 'label',
        'type': 'type',
        'value': 'value'
    }
    if hasattr(SshKeyBaseProperties, "attribute_map"):
        attribute_map.update(SshKeyBaseProperties.attribute_map)

    def __init__(self, password=None, label=None, type=None, value=None, *args, **kwargs):  # noqa: E501
        """SshKeyProperties - a model defined in Swagger"""  # noqa: E501
        self._password = None
        self._label = None
        self._type = None
        self._value = None
        self.discriminator = None
        if password is not None:
            self.password = password
        self.label = label
        self.type = type
        self.value = value
        SshKeyBaseProperties.__init__(self, *args, **kwargs)

    @property
    def password(self):
        """Gets the password of this SshKeyProperties.  # noqa: E501

        Current password for user (required for users root and admin)  # noqa: E501

        :return: The password of this SshKeyProperties.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this SshKeyProperties.

        Current password for user (required for users root and admin)  # noqa: E501

        :param password: The password of this SshKeyProperties.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def label(self):
        """Gets the label of this SshKeyProperties.  # noqa: E501

        SSH key label (used to identify the key)  # noqa: E501

        :return: The label of this SshKeyProperties.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this SshKeyProperties.

        SSH key label (used to identify the key)  # noqa: E501

        :param label: The label of this SshKeyProperties.  # noqa: E501
        :type: str
        """
        if label is None:
            raise ValueError("Invalid value for `label`, must not be `None`")  # noqa: E501

        self._label = label

    @property
    def type(self):
        """Gets the type of this SshKeyProperties.  # noqa: E501

        SSH key type  # noqa: E501

        :return: The type of this SshKeyProperties.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SshKeyProperties.

        SSH key type  # noqa: E501

        :param type: The type of this SshKeyProperties.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def value(self):
        """Gets the value of this SshKeyProperties.  # noqa: E501

        SSH key value  # noqa: E501

        :return: The value of this SshKeyProperties.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this SshKeyProperties.

        SSH key value  # noqa: E501

        :param value: The value of this SshKeyProperties.  # noqa: E501
        :type: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SshKeyProperties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SshKeyProperties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
