# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 2.5.1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TransportNode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'system_owned': 'bool',
        'display_name': 'str',
        'description': 'str',
        'tags': 'list[Tag]',
        'create_user': 'str',
        'protection': 'str',
        'create_time': 'int',
        'last_modified_time': 'int',
        'last_modified_user': 'str',
        'id': 'str',
        'resource_type': 'str',
        'host_switch_spec': 'HostSwitchSpec',
        'node_id': 'str',
        'node_deployment_info': 'Node',
        'host_switches': 'list[HostSwitch]',
        'maintenance_mode': 'str',
        'failure_domain_id': 'str',
        'is_overridden': 'bool',
        'transport_zone_endpoints': 'list[TransportZoneEndPoint]'
    }
    if hasattr(ManagedResource, "swagger_types"):
        swagger_types.update(ManagedResource.swagger_types)

    attribute_map = {
        'system_owned': '_system_owned',
        'display_name': 'display_name',
        'description': 'description',
        'tags': 'tags',
        'create_user': '_create_user',
        'protection': '_protection',
        'create_time': '_create_time',
        'last_modified_time': '_last_modified_time',
        'last_modified_user': '_last_modified_user',
        'id': 'id',
        'resource_type': 'resource_type',
        'host_switch_spec': 'host_switch_spec',
        'node_id': 'node_id',
        'node_deployment_info': 'node_deployment_info',
        'host_switches': 'host_switches',
        'maintenance_mode': 'maintenance_mode',
        'failure_domain_id': 'failure_domain_id',
        'is_overridden': 'is_overridden',
        'transport_zone_endpoints': 'transport_zone_endpoints'
    }
    if hasattr(ManagedResource, "attribute_map"):
        attribute_map.update(ManagedResource.attribute_map)

    def __init__(self, system_owned=None, display_name=None, description=None, tags=None, create_user=None, protection=None, create_time=None, last_modified_time=None, last_modified_user=None, id=None, resource_type=None, host_switch_spec=None, node_id=None, node_deployment_info=None, host_switches=None, maintenance_mode=None, failure_domain_id=None, is_overridden=None, transport_zone_endpoints=None, *args, **kwargs):  # noqa: E501
        """TransportNode - a model defined in Swagger"""  # noqa: E501
        self._system_owned = None
        self._display_name = None
        self._description = None
        self._tags = None
        self._create_user = None
        self._protection = None
        self._create_time = None
        self._last_modified_time = None
        self._last_modified_user = None
        self._id = None
        self._resource_type = None
        self._host_switch_spec = None
        self._node_id = None
        self._node_deployment_info = None
        self._host_switches = None
        self._maintenance_mode = None
        self._failure_domain_id = None
        self._is_overridden = None
        self._transport_zone_endpoints = None
        self.discriminator = None
        if system_owned is not None:
            self.system_owned = system_owned
        if display_name is not None:
            self.display_name = display_name
        if description is not None:
            self.description = description
        if tags is not None:
            self.tags = tags
        if create_user is not None:
            self.create_user = create_user
        if protection is not None:
            self.protection = protection
        if create_time is not None:
            self.create_time = create_time
        if last_modified_time is not None:
            self.last_modified_time = last_modified_time
        if last_modified_user is not None:
            self.last_modified_user = last_modified_user
        if id is not None:
            self.id = id
        if resource_type is not None:
            self.resource_type = resource_type
        if host_switch_spec is not None:
            self.host_switch_spec = host_switch_spec
        if node_id is not None:
            self.node_id = node_id
        if node_deployment_info is not None:
            self.node_deployment_info = node_deployment_info
        if host_switches is not None:
            self.host_switches = host_switches
        if maintenance_mode is not None:
            self.maintenance_mode = maintenance_mode
        if failure_domain_id is not None:
            self.failure_domain_id = failure_domain_id
        if is_overridden is not None:
            self.is_overridden = is_overridden
        if transport_zone_endpoints is not None:
            self.transport_zone_endpoints = transport_zone_endpoints
        ManagedResource.__init__(self, *args, **kwargs)

    @property
    def system_owned(self):
        """Gets the system_owned of this TransportNode.  # noqa: E501

        Indicates system owned resource  # noqa: E501

        :return: The system_owned of this TransportNode.  # noqa: E501
        :rtype: bool
        """
        return self._system_owned

    @system_owned.setter
    def system_owned(self, system_owned):
        """Sets the system_owned of this TransportNode.

        Indicates system owned resource  # noqa: E501

        :param system_owned: The system_owned of this TransportNode.  # noqa: E501
        :type: bool
        """

        self._system_owned = system_owned

    @property
    def display_name(self):
        """Gets the display_name of this TransportNode.  # noqa: E501

        Defaults to ID if not set  # noqa: E501

        :return: The display_name of this TransportNode.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this TransportNode.

        Defaults to ID if not set  # noqa: E501

        :param display_name: The display_name of this TransportNode.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def description(self):
        """Gets the description of this TransportNode.  # noqa: E501

        Description of this resource  # noqa: E501

        :return: The description of this TransportNode.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TransportNode.

        Description of this resource  # noqa: E501

        :param description: The description of this TransportNode.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def tags(self):
        """Gets the tags of this TransportNode.  # noqa: E501

        Opaque identifiers meaningful to the API user  # noqa: E501

        :return: The tags of this TransportNode.  # noqa: E501
        :rtype: list[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this TransportNode.

        Opaque identifiers meaningful to the API user  # noqa: E501

        :param tags: The tags of this TransportNode.  # noqa: E501
        :type: list[Tag]
        """

        self._tags = tags

    @property
    def create_user(self):
        """Gets the create_user of this TransportNode.  # noqa: E501

        ID of the user who created this resource  # noqa: E501

        :return: The create_user of this TransportNode.  # noqa: E501
        :rtype: str
        """
        return self._create_user

    @create_user.setter
    def create_user(self, create_user):
        """Sets the create_user of this TransportNode.

        ID of the user who created this resource  # noqa: E501

        :param create_user: The create_user of this TransportNode.  # noqa: E501
        :type: str
        """

        self._create_user = create_user

    @property
    def protection(self):
        """Gets the protection of this TransportNode.  # noqa: E501

        Protection status is one of the following: PROTECTED - the client who retrieved the entity is not allowed             to modify it. NOT_PROTECTED - the client who retrieved the entity is allowed                 to modify it REQUIRE_OVERRIDE - the client who retrieved the entity is a super                    user and can modify it, but only when providing                    the request header X-Allow-Overwrite=true. UNKNOWN - the _protection field could not be determined for this           entity.   # noqa: E501

        :return: The protection of this TransportNode.  # noqa: E501
        :rtype: str
        """
        return self._protection

    @protection.setter
    def protection(self, protection):
        """Sets the protection of this TransportNode.

        Protection status is one of the following: PROTECTED - the client who retrieved the entity is not allowed             to modify it. NOT_PROTECTED - the client who retrieved the entity is allowed                 to modify it REQUIRE_OVERRIDE - the client who retrieved the entity is a super                    user and can modify it, but only when providing                    the request header X-Allow-Overwrite=true. UNKNOWN - the _protection field could not be determined for this           entity.   # noqa: E501

        :param protection: The protection of this TransportNode.  # noqa: E501
        :type: str
        """

        self._protection = protection

    @property
    def create_time(self):
        """Gets the create_time of this TransportNode.  # noqa: E501

        Timestamp of resource creation  # noqa: E501

        :return: The create_time of this TransportNode.  # noqa: E501
        :rtype: int
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this TransportNode.

        Timestamp of resource creation  # noqa: E501

        :param create_time: The create_time of this TransportNode.  # noqa: E501
        :type: int
        """

        self._create_time = create_time

    @property
    def last_modified_time(self):
        """Gets the last_modified_time of this TransportNode.  # noqa: E501

        Timestamp of last modification  # noqa: E501

        :return: The last_modified_time of this TransportNode.  # noqa: E501
        :rtype: int
        """
        return self._last_modified_time

    @last_modified_time.setter
    def last_modified_time(self, last_modified_time):
        """Sets the last_modified_time of this TransportNode.

        Timestamp of last modification  # noqa: E501

        :param last_modified_time: The last_modified_time of this TransportNode.  # noqa: E501
        :type: int
        """

        self._last_modified_time = last_modified_time

    @property
    def last_modified_user(self):
        """Gets the last_modified_user of this TransportNode.  # noqa: E501

        ID of the user who last modified this resource  # noqa: E501

        :return: The last_modified_user of this TransportNode.  # noqa: E501
        :rtype: str
        """
        return self._last_modified_user

    @last_modified_user.setter
    def last_modified_user(self, last_modified_user):
        """Sets the last_modified_user of this TransportNode.

        ID of the user who last modified this resource  # noqa: E501

        :param last_modified_user: The last_modified_user of this TransportNode.  # noqa: E501
        :type: str
        """

        self._last_modified_user = last_modified_user

    @property
    def id(self):
        """Gets the id of this TransportNode.  # noqa: E501

        Unique identifier of this resource  # noqa: E501

        :return: The id of this TransportNode.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TransportNode.

        Unique identifier of this resource  # noqa: E501

        :param id: The id of this TransportNode.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def resource_type(self):
        """Gets the resource_type of this TransportNode.  # noqa: E501

        The type of this resource.  # noqa: E501

        :return: The resource_type of this TransportNode.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this TransportNode.

        The type of this resource.  # noqa: E501

        :param resource_type: The resource_type of this TransportNode.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def host_switch_spec(self):
        """Gets the host_switch_spec of this TransportNode.  # noqa: E501


        :return: The host_switch_spec of this TransportNode.  # noqa: E501
        :rtype: HostSwitchSpec
        """
        return self._host_switch_spec

    @host_switch_spec.setter
    def host_switch_spec(self, host_switch_spec):
        """Sets the host_switch_spec of this TransportNode.


        :param host_switch_spec: The host_switch_spec of this TransportNode.  # noqa: E501
        :type: HostSwitchSpec
        """

        self._host_switch_spec = host_switch_spec

    @property
    def node_id(self):
        """Gets the node_id of this TransportNode.  # noqa: E501

        Unique Id of the fabric node  # noqa: E501

        :return: The node_id of this TransportNode.  # noqa: E501
        :rtype: str
        """
        return self._node_id

    @node_id.setter
    def node_id(self, node_id):
        """Sets the node_id of this TransportNode.

        Unique Id of the fabric node  # noqa: E501

        :param node_id: The node_id of this TransportNode.  # noqa: E501
        :type: str
        """

        self._node_id = node_id

    @property
    def node_deployment_info(self):
        """Gets the node_deployment_info of this TransportNode.  # noqa: E501


        :return: The node_deployment_info of this TransportNode.  # noqa: E501
        :rtype: Node
        """
        return self._node_deployment_info

    @node_deployment_info.setter
    def node_deployment_info(self, node_deployment_info):
        """Sets the node_deployment_info of this TransportNode.


        :param node_deployment_info: The node_deployment_info of this TransportNode.  # noqa: E501
        :type: Node
        """

        self._node_deployment_info = node_deployment_info

    @property
    def host_switches(self):
        """Gets the host_switches of this TransportNode.  # noqa: E501

        This property is deprecated in favor of 'host_switch_spec'. Property 'host_switches' can only be used for NSX managed transport nodes. 'host_switch_spec' can be used for both NSX managed or manually preconfigured host switches.  # noqa: E501

        :return: The host_switches of this TransportNode.  # noqa: E501
        :rtype: list[HostSwitch]
        """
        return self._host_switches

    @host_switches.setter
    def host_switches(self, host_switches):
        """Sets the host_switches of this TransportNode.

        This property is deprecated in favor of 'host_switch_spec'. Property 'host_switches' can only be used for NSX managed transport nodes. 'host_switch_spec' can be used for both NSX managed or manually preconfigured host switches.  # noqa: E501

        :param host_switches: The host_switches of this TransportNode.  # noqa: E501
        :type: list[HostSwitch]
        """

        self._host_switches = host_switches

    @property
    def maintenance_mode(self):
        """Gets the maintenance_mode of this TransportNode.  # noqa: E501

        The property is read-only, used for querying result. User could update transport node maintenance mode by UpdateTransportNodeMaintenanceMode call.  # noqa: E501

        :return: The maintenance_mode of this TransportNode.  # noqa: E501
        :rtype: str
        """
        return self._maintenance_mode

    @maintenance_mode.setter
    def maintenance_mode(self, maintenance_mode):
        """Sets the maintenance_mode of this TransportNode.

        The property is read-only, used for querying result. User could update transport node maintenance mode by UpdateTransportNodeMaintenanceMode call.  # noqa: E501

        :param maintenance_mode: The maintenance_mode of this TransportNode.  # noqa: E501
        :type: str
        """
        allowed_values = ["ENABLED", "FORCE_ENABLED", "DISABLED"]  # noqa: E501
        if maintenance_mode not in allowed_values:
            raise ValueError(
                "Invalid value for `maintenance_mode` ({0}), must be one of {1}"  # noqa: E501
                .format(maintenance_mode, allowed_values)
            )

        self._maintenance_mode = maintenance_mode

    @property
    def failure_domain_id(self):
        """Gets the failure_domain_id of this TransportNode.  # noqa: E501

        Set failure domain of edge transport node which will help in auto placement of TIER1 logical routers, DHCP Servers and MDProxies, if failure domain based allocation is enabled in edge cluster API. It is only supported for edge transport node and not for host transport node. In case failure domain is not set by user explicitly, it will be always assigned with default system created failure domain.   # noqa: E501

        :return: The failure_domain_id of this TransportNode.  # noqa: E501
        :rtype: str
        """
        return self._failure_domain_id

    @failure_domain_id.setter
    def failure_domain_id(self, failure_domain_id):
        """Sets the failure_domain_id of this TransportNode.

        Set failure domain of edge transport node which will help in auto placement of TIER1 logical routers, DHCP Servers and MDProxies, if failure domain based allocation is enabled in edge cluster API. It is only supported for edge transport node and not for host transport node. In case failure domain is not set by user explicitly, it will be always assigned with default system created failure domain.   # noqa: E501

        :param failure_domain_id: The failure_domain_id of this TransportNode.  # noqa: E501
        :type: str
        """

        self._failure_domain_id = failure_domain_id

    @property
    def is_overridden(self):
        """Gets the is_overridden of this TransportNode.  # noqa: E501

        This flag is relevant to only those hosts which are part of a compute collection which has transport node profile (TNP) applied on it. If you change the transport node configuration and it is different than cluster level TNP then this flag will be set to true   # noqa: E501

        :return: The is_overridden of this TransportNode.  # noqa: E501
        :rtype: bool
        """
        return self._is_overridden

    @is_overridden.setter
    def is_overridden(self, is_overridden):
        """Sets the is_overridden of this TransportNode.

        This flag is relevant to only those hosts which are part of a compute collection which has transport node profile (TNP) applied on it. If you change the transport node configuration and it is different than cluster level TNP then this flag will be set to true   # noqa: E501

        :param is_overridden: The is_overridden of this TransportNode.  # noqa: E501
        :type: bool
        """

        self._is_overridden = is_overridden

    @property
    def transport_zone_endpoints(self):
        """Gets the transport_zone_endpoints of this TransportNode.  # noqa: E501

        Transport zone endpoints.  # noqa: E501

        :return: The transport_zone_endpoints of this TransportNode.  # noqa: E501
        :rtype: list[TransportZoneEndPoint]
        """
        return self._transport_zone_endpoints

    @transport_zone_endpoints.setter
    def transport_zone_endpoints(self, transport_zone_endpoints):
        """Sets the transport_zone_endpoints of this TransportNode.

        Transport zone endpoints.  # noqa: E501

        :param transport_zone_endpoints: The transport_zone_endpoints of this TransportNode.  # noqa: E501
        :type: list[TransportZoneEndPoint]
        """

        self._transport_zone_endpoints = transport_zone_endpoints

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransportNode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransportNode):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
